-- 0001_init.down.sql
DROP TABLE IF EXISTS sidepanel;
DROP TABLE IF EXISTS languages;
DROP TABLE IF EXISTS contact;
DROP TABLE IF EXISTS partners;
DROP TABLE IF EXISTS news;
DROP TABLE IF EXISTS services;
DROP TABLE IF EXISTS about;
DROP TABLE IF EXISTS stats;
DROP TABLE IF EXISTS hero_slides;
DROP TABLE IF EXISTS admin_password;
DROP TABLE IF EXISTS site;
