package service

// DefaultLanguages returns seed data for all supported languages.
// Called on first boot and when migrating missing languages.
func DefaultLanguages() map[string]map[string]string {
	return map[string]map[string]string{
		"en": {
			"flag": "🇬🇧", "name": "English",
			"nav_home": "Home", "nav_about": "About", "nav_services": "Services", "nav_news": "News", "nav_quote": "Get Quote",
			"eyebrow_who": "Who We Are", "eyebrow_offer": "What We Offer", "eyebrow_updates": "Latest Updates",
			"eyebrow_partners": "Trusted By", "eyebrow_touch": "Get In Touch",
			"sec_about": "About Us", "sec_services": "Our Services", "sec_news": "Our News", "sec_partners": "Our Key Partners",
			"cta_title": "Ready to Ship With Us?", "cta_sub": "Contact our team for a custom logistics solution.",
			"cta_btn": "Request a Quote →", "about_btn": "Contact Us →", "slide_tag": "Global Logistics",
			"slide_title": "Global Logistics Solutions", "slide_subtitle": "Fast, Reliable & Trusted Worldwide", "slide_btn_text": "Explore",
			"footer_services": "Services", "footer_company": "Company", "footer_team": "Team",
			"footer_careers": "Careers", "footer_news": "News", "footer_contact": "Contact", "years": "Years",
			"footer_tagline": "Connecting the World, Delivering Excellence since 2001.",
			"page_title": "NexLog Global — International Logistics", "rights": "All Rights Reserved",
		},
		"ru": {
			"flag": "🇷🇺", "name": "Русский",
			"nav_home": "Главная", "nav_about": "О нас", "nav_services": "Услуги", "nav_news": "Новости", "nav_quote": "Запрос",
			"eyebrow_who": "Кто мы", "eyebrow_offer": "Что мы предлагаем", "eyebrow_updates": "Последние новости",
			"eyebrow_partners": "Нам доверяют", "eyebrow_touch": "Связаться с нами",
			"sec_about": "О компании", "sec_services": "Наши услуги", "sec_news": "Новости", "sec_partners": "Наши партнёры",
			"cta_title": "Готовы отправить груз?", "cta_sub": "Свяжитесь с нашей командой для решения логистических задач.",
			"cta_btn": "Запросить цену →", "about_btn": "Связаться →", "slide_tag": "Глобальная логистика",
			"slide_title": "Глобальные логистические решения", "slide_subtitle": "Быстро, надёжно и с доверием по всему миру", "slide_btn_text": "Узнать больше",
			"footer_services": "Услуги", "footer_company": "Компания", "footer_team": "Команда",
			"footer_careers": "Карьера", "footer_news": "Новости", "footer_contact": "Контакты", "years": "Лет",
			"footer_tagline": "Объединяем мир, обеспечивая совершенство с 2001 года.",
			"page_title": "NexLog Global — Международная логистика", "rights": "Все права защищены",
		},
		"ja": {
			"flag": "🇯🇵", "name": "日本語",
			"nav_home": "ホーム", "nav_about": "会社概要", "nav_services": "サービス", "nav_news": "ニュース", "nav_quote": "見積もり",
			"eyebrow_who": "私たちについて", "eyebrow_offer": "サービス内容", "eyebrow_updates": "最新ニュース",
			"eyebrow_partners": "信頼されています", "eyebrow_touch": "お問い合わせ",
			"sec_about": "会社概要", "sec_services": "サービス", "sec_news": "ニュース", "sec_partners": "主要パートナー",
			"cta_title": "一緒に出荷しませんか？", "cta_sub": "お客様のニーズに合った物流ソリューションについて、チームにお問い合わせください。",
			"cta_btn": "見積もりを依頼する →", "about_btn": "お問い合わせ →", "slide_tag": "グローバル物流",
			"slide_title": "グローバル物流ソリューション", "slide_subtitle": "迅速・確実・世界中で信頼される", "slide_btn_text": "詳しく見る",
			"footer_services": "サービス", "footer_company": "会社", "footer_team": "チーム",
			"footer_careers": "採用情報", "footer_news": "ニュース", "footer_contact": "お問い合わせ", "years": "年",
			"footer_tagline": "2001年から世界をつなぎ、卓越したサービスをお届けしています。",
			"page_title": "NexLog Global — 国際物流", "rights": "全著作権所有",
		},
		"tk": {
			"flag": "🇹🇲", "name": "Türkmen",
			"nav_home": "Baş sahypa", "nav_about": "Biz hakda", "nav_services": "Hyzmatlar", "nav_news": "Habarlar", "nav_quote": "Teklip al",
			"eyebrow_who": "Biz kimler", "eyebrow_offer": "Näme hödürleýäris", "eyebrow_updates": "Soňky habarlar",
			"eyebrow_partners": "Bize ynanýarlar", "eyebrow_touch": "Habarlaşyň",
			"sec_about": "Biz hakda", "sec_services": "Hyzmatlarymyz", "sec_news": "Habarlar", "sec_partners": "Esasy hyzmatdaşlar",
			"cta_title": "Biz bilen ibermäge taýynmy?", "cta_sub": "Öz zerurlyklaryňyza laýyk logistika çözgüdi üçin toparymyz bilen habarlaşyň.",
			"cta_btn": "Teklip soramak →", "about_btn": "Habarlaşmak →", "slide_tag": "Global logistika",
			"slide_title": "Global logistika çözgütleri", "slide_subtitle": "Çalt, ynamdar we dünýä boýunça ynanylýan", "slide_btn_text": "Öwren",
			"footer_services": "Hyzmatlar", "footer_company": "Kompaniýa", "footer_team": "Topar",
			"footer_careers": "Iş orunlary", "footer_news": "Habarlar", "footer_contact": "Habarlaşmak", "years": "Ýyl",
			"footer_tagline": "2001-nji ýyldan bäri dünýäni birikdirip, ajaýyplygy üpjün edýäris.",
			"page_title": "NexLog Global — Halkara logistika", "rights": "Ähli hukuklar goralan",
		},
		"zh": {
			"flag": "🇨🇳", "name": "中文",
			"nav_home": "首页", "nav_about": "关于我们", "nav_services": "服务", "nav_news": "新闻", "nav_quote": "获取报价",
			"eyebrow_who": "我们是谁", "eyebrow_offer": "我们提供什么", "eyebrow_updates": "最新动态",
			"eyebrow_partners": "合作伙伴", "eyebrow_touch": "联系我们",
			"sec_about": "关于我们", "sec_services": "我们的服务", "sec_news": "新闻资讯", "sec_partners": "主要合作伙伴",
			"cta_title": "准备好与我们合作了吗？", "cta_sub": "联系我们的团队，获取专属物流解决方案。",
			"cta_btn": "申请报价 →", "about_btn": "联系我们 →", "slide_tag": "全球物流",
			"slide_title": "全球物流解决方案", "slide_subtitle": "快速、可靠、值得全球信赖", "slide_btn_text": "了解更多",
			"footer_services": "服务", "footer_company": "公司", "footer_team": "团队",
			"footer_careers": "招聘", "footer_news": "新闻", "footer_contact": "联系我们", "years": "年",
			"footer_tagline": "自2001年以来连接世界，缔造卓越。",
			"page_title": "NexLog Global — 国际物流", "rights": "版权所有",
		},
	}
}
